### ISSUE TITLE
Shut down instance and associated resources

### ISSUE THREAD

**Issue by hectcastro** [azavea/idb-omk-pilot#11]
Before tearing the server down, create an AMI.

Afterwards, tear down the OMK EC2 instance that was created in https://github.com/azavea/idb-omk-pilot/issues/4. In the process, make sure that any out-of-band credentials or resources are torn down as well (DNS, IAM, etc.).

**Comment by coalkettler** [comment]
@hectcastro I've created an AMI with EBS snapshot for the currently running instance and verified that the application works on creating an instance from the AMI and opening up 80/TCP to ingress traffic.

The following resources have been deleted / released:
- Old OpenMapKit EC2 instance, EBS volume, and automatically generated security group
- Current OpenMapKit EC2 instance, EBS volume, and automatically generated security group
- Route 53 hosted zone associated with current OpenMapKit EC2 instance
- Elastic IP associated with current OpenMapKit EC2 instance

I didn't see any other resources (like IAM users / policies) created to support this instance. Passing this to you for review if you'd like to verify 🔍

**Comment by hectcastro** [comment]
I have reassigned @rbreslow for review because he worked on this task originally. 

I vaguely recall there being an IAM user associated with this effort (possibly in another account) to help renew a Let's Encrypt TLS certificate via DNS validation, but your reference to port 80 decreases my confidence in that memory.

**Comment by coalkettler** [comment]
@hectcastro There could still be an IAM user in another account. I believe `443` was open as well, I just needed to open `80` because I was testing against the public DNS for the EC2 instance without TLS.

The only IAM users I see in the account with the previously running instance are individual user accounts or accounts related to CI / Heroku.

**Comment by rbreslow** [comment]
I had to clean up an IAM role, an EC2 security group, and NS records left over in the Azavea Systems AWS account. 

Other than that, looks 👍.

**Comment by coalkettler** [comment]
I think the security group was from an EC2 instance that I had just created to check the `crontab`, my bad! Thanks for the cleanup! 💪
